-- local MouthLower = workspace.Studio.Tmp.SoundRepeat.Lock.Lock.MouthLower
-- MouthLower:PivotTo(MouthLower:GetPivot() * CFrame.Angles(0, 0.5 * math.pi, 0))
-- MouthLower.CFrame = CFrame.new(298.362, 34.249, 842.392) * CFrame.fromOrientation(0.25 * math.pi, 0, -0.5 * math.pi)