-- local ReplicatedStorage = game:GetService("ReplicatedStorage")

-- local ComposedKey = require(ReplicatedStorage.TableUtils.ComposedKey)
-- local Mod = require(ComposedKey.getAsync(ReplicatedStorage, {"Sherlocks", "Shared", "Mod"}))
-- local Promise = Mod:find({"Promise", "Promise"})

-- local p1 = Promise.try(function()
--     print("z1")
--     error("Promise error")
-- end)
-- -- :andThen(function()
-- --     print("z2")
-- -- end)
-- -- :catch(function()
-- --     print("z3")
-- -- end)
-- :finally(function()
--     print("z4")
-- end)